### ISSUE TITLE
NextAuth

### ISSUE THREAD

**Issue by alexthewilde** [chamatt/create-kaol-app#5]
Hi @chamatt, you've done a pretty decent job here. Everything has been working out of the box for me. Sweet!

You mention in the README that this starter has been inspired by the t3 stack. So I'm wondering why you've decided against using NextAuth and instead roll your own authentication mechanism?

With the availability of all the [providers](https://next-auth.js.org/providers/) and [adapters](https://next-auth.js.org/adapters/overview), NextAuth has become a no-brainer in many projects.

Would you consider creating a separate branch with a working NextAuth integration?

**Comment by chamatt** [comment]
Thank you! Glad it's working for you

The only reason I've decided against NextAuth is because it currently doesn't have any integrations for react native, and I'm not skilled enough nor have a deep enough understanding of next auth to roll out my own. I've seem some initiatives on the project issues tab to make it happen, so once something useable comes up I'll try integrating

**Comment by alexthewilde** [comment]
Sounds good 👍
